# Craig Tomkow
# July 26, 2019
# Yaml file defining Google App environment

runtime: python37
instance_class: F2

entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto